### ISSUE TITLE
Beefs with recent core team's rules import.

### ISSUE THREAD

**Issue by beporter** [loadsys/loadsys_codesniffer#13]
* Mandating (single) spaces in `@attr` docblock arguments I think makes them extremely hard to read (vs "lined up" tabs) but I realize that tabs are inconsistent at best across platforms/editors/devs/etc. Maybe just counting tabs as "spaces" would be sufficient? Needs discussion?
* I'm all for not **forcing** underscores on protected properties/methods, but I also think there are cases where using an underscore either serves a purpose (such as signaling intent to other developers other than visibility) or at the very last doesn't actually _hurt_ anything. One example is `AppController::_auth()` which is not necessarily "protected", but should not be called as a routed URL (it's a controller-internal "assistive" method, not an "action".) Previously I had these sniffs completely suppressed in the XML config. They were there, and they were still processed, the report just didn't actually complain about it at all. I'm open to compelling counter arguments, but this would be my preference.

Even though the update caused a ton of warnings in a previously-up-to-date project, the rest are warranted and should be easy to fix (especially with php_codesniffer v2.0.)

**Comment by jtyost2** [comment]
Closing as we should have solved this in the 3.x branch.
