### ISSUE TITLE
Change `_` in method names to be a warning as CakePHP 3.x currently still has these in a lot of places

### ISSUE THREAD

**Issue by jtyost2** [loadsys/loadsys_codesniffer#25]
Then add information to suppress warnings via the `-n` cli option for travis builds.

**Comment by jtyost2** [comment]
This has not been fixed.

**Comment by jtyost2** [comment]
@beporter Need to discuss this.

The `type` flag in the `ruleset.xml` doesn't appear to be working based upon my usage of this.

![screen shot 2015-07-11 at 5 35 04 pm](https://cloud.githubusercontent.com/assets/85320/8635872/326f2a78-27f3-11e5-810f-56ecbc694b42.png)
![screen shot 2015-07-11 at 5 35 43 pm](https://cloud.githubusercontent.com/assets/85320/8635874/45990c36-27f3-11e5-87cd-68c1b44eb868.png)

Based on my testing only changing the method call from Error/Warning seems to work in this repo itself.

**Comment by jtyost2** [comment]
I cleared the Travis Caches for the ConfigReadShell Plugin,

Re-kicked off a build and verified it download the Code Sniffer with this change in place: https://travis-ci.org/loadsys/CakePHP-ConfigReadShell/builds/69979194#L227 and https://github.com/loadsys/loadsys_codesniffer/releases/tag/3.0.2

It still reports the `_` in a method name as an error: https://travis-ci.org/loadsys/CakePHP-ConfigReadShell/builds/69979194#L252

**Comment by beporter** [comment]
Fixed in #38, I believe.

**Comment by jtyost2** [comment]
Verified.
