### ISSUE TITLE
Remove fork association?

### ISSUE THREAD

**Issue by beporter** [loadsys/loadsys_codesniffer#30]
Is there a significant benefit to maintaining the ancestor/child relationship with `cakephp/cakephp-codesniffer`? I know we may still want to import their changes, but do we need to preserve the formal fork relationship for that?

**Comment by jtyost2** [comment]
Note only way to deattach a Fork is to contact support: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

**Comment by jtyost2** [comment]
And I vote yes.

**Comment by jtyost2** [comment]
Thanks @beporter

**Comment by beporter** [comment]
Pasting email response from GitHub support (verbatim):

> Hi Brian,
> 
> [Done!](https://www.youtube.com/watch?v=gr_OpFxCx-A&amp;t=1m43s) I have detached that fork for you.
> 
> Cheers,
> Scott
