### ISSUE TITLE
Verify Short Array Syntax is preferred

### ISSUE THREAD

**Issue by jtyost2** [loadsys/loadsys_codesniffer#31]

**Comment by jtyost2** [comment]
@loadsys/developers Do we want to have our codesniffer check for Short Array Syntax and throw a warning when it's not used?

We have the option to only dis-allow one or the other: https://github.com/squizlabs/PHP_CodeSniffer/tree/master/CodeSniffer/Standards/Generic/Sniffs/Arrays

I believe.

**Comment by beporter** [comment]
Yes. Our Cake 3 skeleton already dictates/mandates PHP 5.6. I say we mandate short array syntax as well. :+1:
